import { buildParkDay, type RoteiroRow } from './shared';

const ROWS: RoteiroRow[] = [
  [1, 'Seven Dwarfs Mine Train', 'Fantasyland', 'attraction', 'S', { lightningLane: 'individual' }],
  [2, "Peter Pan's Flight", 'Fantasyland', 'attraction', 'S', { lightningLane: 'genie_plus', lightningLaneRank: 2 }],
  [3, 'The Many Adventures of Winnie the Pooh', 'Fantasyland', 'attraction', 'A', { lightningLane: 'genie_plus', lightningLaneRank: 5 }],
  [4, 'Mad Tea Party', 'Fantasyland', 'attraction', 'B'],
  [5, 'Prince Charming Regal Carrousel', 'Fantasyland', 'attraction', 'B'],
  [6, "it's a small world", 'Fantasyland', 'attraction', 'A'],
  [7, "Mickey's PhilharMagic", 'Fantasyland', 'attraction', 'A'],
  [8, 'Dumbo the Flying Elephant', 'Storybook Circus', 'attraction', 'A'],
  [9, 'The Barnstormer', 'Storybook Circus', 'attraction', 'B'],
  [10, "Casey Jr. Splash 'N' Soak Station", 'Storybook Circus', 'experience', 'C'],
  [11, 'Smellephants on Parade', 'Storybook Circus', 'experience', 'C'],
  [12, 'Under the Sea – Journey of the Little Mermaid', 'Fantasyland', 'attraction', 'A'],
  [13, 'Enchanted Tales with Belle', 'Fantasyland', 'experience', 'B'],
  [14, 'Meet Ariel at Her Grotto', 'Fantasyland', 'character', undefined, { description: 'Encontro opcional de personagem, com métrica de cobertura própria.' }],
  [15, 'Tomorrowland Speedway', 'Tomorrowland', 'attraction', 'B'],
  [16, 'TRON Lightcycle / Run', 'Tomorrowland', 'attraction', 'S', { lightningLane: 'individual' }],
  [17, 'Space Mountain', 'Tomorrowland', 'attraction', 'S', { lightningLane: 'genie_plus', lightningLaneRank: 4 }],
  [18, 'Astro Orbiter', 'Tomorrowland', 'attraction', 'B'],
  [19, 'Tomorrowland Transit Authority PeopleMover', 'Tomorrowland', 'attraction', 'A'],
  [20, "Walt Disney's Carousel of Progress", 'Tomorrowland', 'attraction', 'B'],
  [21, 'Monsters, Inc. Laugh Floor', 'Tomorrowland', 'attraction', 'A'],
  [22, "Buzz Lightyear's Space Ranger Spin", 'Tomorrowland', 'attraction', 'A'],
  [23, 'Haunted Mansion', 'Liberty Square', 'attraction', 'S', { lightningLane: 'genie_plus', lightningLaneRank: 6 }],
  [24, 'The Hall of Presidents', 'Liberty Square', 'attraction', 'B'],
  [25, 'Country Bear Musical Jamboree', 'Frontierland', 'attraction', 'A'],
  [26, "Tiana's Bayou Adventure", 'Frontierland', 'attraction', 'S', { lightningLane: 'genie_plus', lightningLaneRank: 1 }],
  [27, 'Big Thunder Mountain Railroad', 'Frontierland', 'attraction', 'S'],
  [28, 'Pirates of the Caribbean', 'Adventureland', 'attraction', 'S'],
  [29, "A Pirate's Adventure – Treasures of the Seven Seas", 'Adventureland', 'experience', 'C'],
  [30, 'Jungle Cruise', 'Adventureland', 'attraction', 'S', { lightningLane: 'genie_plus', lightningLaneRank: 3 }],
  [31, 'The Magic Carpets of Aladdin', 'Adventureland', 'attraction', 'B'],
  [32, "Walt Disney's Enchanted Tiki Room", 'Adventureland', 'attraction', 'B'],
  [33, 'Swiss Family Treehouse', 'Adventureland', 'attraction', 'C'],
  [34, 'Walt Disney World Railroad', 'Main Street, U.S.A.', 'attraction', 'B', { earlyClosureRisk: true }],
  [35, 'Main Street Vehicles', 'Main Street, U.S.A.', 'attraction', 'C', { earlyClosureRisk: true, description: 'Rodar somente se estiver operando no dia.' }],
  [36, 'Disney Adventure Friends Cavalcade', 'Castelo / rota do desfile', 'show'],
  [37, "Mickey's Magical Friendship Faire", 'Castelo / rota do desfile', 'show'],
  [38, 'Disney Festival of Fantasy Parade', 'Castelo / rota do desfile', 'show'],
  [39, 'Disney Starlight: Dream the Night Away', 'Castelo / rota do desfile', 'show'],
  [40, 'Happily Ever After', 'Castelo / rota do desfile', 'show', undefined, { lastShowtimeOfDay: true, description: 'Show final obrigatório de fogos.' }],
];

export const MAGIC_KINGDOM_ITEMS = buildParkDay(
  {
    parkKey: 'mk',
    parkName: 'Magic Kingdom',
    city: 'Lake Buena Vista',
    date: '2026-09-07',
    openTime: '08:30',
    closeTime: '21:00',
  },
  ROWS
);
